application: buckleyapp
version: 1
runtime: python
api_version: 1
default_expiration: '1h'

handlers:
# Cache handlers
# I use these on my blog. I generate static files locally and then deploy.
# in high-traffic situations this works best. Either generate all your posts
# or just the posts that are getting a lot of traffic. 
# - url: /posts/(.*)
#   static_files: cache/\1
#   upload: cache/(.*)
#   mime_type: text/html
#   expiration: 10m
# - url: /(contact|about|archive|consulting|projects)
#   static_files: cache/\1
#   upload: cache/(.*)
#   mime_type: text/html
#   expiration: 1h
# - url: /
#   static_files: cache/index
#   upload: cache/index
#   mime_type: text/html
#   expiration: 5m

# Static files
- url: /css
  mime_type: text/css
  expiration: 10000d
  static_dir: static/css
- url: /img
  static_dir: static/img
  expiration: 10000d
- url: /js
  static_dir: static/js
  expiration: 10000d

# Dynamic load
# dynamic loading is quick anyway, uses memcache
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  
- url: .*
  script: main.py
  


builtins:
- datastore_admin: on
- appstats: on
- admin_redirect: on
- remote_api: on

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?index\.yaml
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/git/.*
- ^(.*/)?.*/svn/.*
- ^(.*/)?\..*
- ^(.*/)?README$
- ^(.*/)?.*\.bak$

